# Generated by Django 2.2.12 on 2021-08-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='author',
            new_name='owner',
        ),
    ]
