# Generated by Django 2.2.12 on 2021-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210822_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='add_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
