# Generated by Django 2.2.12 on 2021-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='on_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
